name: elementary_test
description: A testing library which makes it easy to test elementary used apps. Built to be used with the elementary architecture package.
version: 1.0.1
repository: "https://github.com/Elementary-team/flutter-elementary/tree/main/packages/elementary_test"
issue_tracker: "https://github.com/Elementary-team/flutter-elementary/issues"
homepage: "https://github.com/Elementary-team/flutter-elementary"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  elementary: ^1.0.0
  mocktail: ^0.2.0
  meta: ^1.3.0

dev_dependencies:
  surf_lint_rules: ^1.0.0
