name: elementary_test
description: A testing library which makes it easy to test elementary used apps. Built to be used with the elementary architecture package.
version: 2.1.1
repository: "https://github.com/Elementary-team/flutter-elementary/tree/main/packages/elementary_test"
issue_tracker: "https://github.com/Elementary-team/flutter-elementary/issues"
homepage: "https://github.com/Elementary-team/flutter-elementary"

funding:
  - https://github.com/sponsors/MbIXjkee
  - https://buymeacoffee.com/mbixjkee
  - https://www.patreon.com/MbIXJkee
  - https://boosty.to/mbixjkee

topics:
  - mvvm
  - architecture
  - state-management
  - elementary
  - testing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  elementary: ^3.2.0
  mocktail: ^1.0.0
  meta: ^1.8.0

dev_dependencies:
  mjk_lint_rules: ^2.0.0
