name: analyzer_plugin_bootstrap
description: Elementary analyzer plugin
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  elementary_cli: ^0.0.2

dev_dependencies:
  surf_lint_rules: ^1.0.0
