/// List of interests from the mock server.
const List<String> mockInterestsList = <String>[
  'Photo',
  'Art',
  'Flowers',
  'Quotes',
  'Design',
  'Illustrations',
  'Home decor',
  'Fashion',
  'Humor',
  'Food and drink',
  'Outdoor activities',
  'Sports',
  'Travel',
  'Reading',
  'Sleep',
  'Geography',
  'Science',
  'Space',
  'Programming',
  'High technology',
  'Politics',
  'Theatre',
  'Cinema',
  'Modeling',
];
