name: counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  elementary:
    path: ../
  elementary_helper:
    path: ../../elementary_helper
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  mjk_lint_rules: ^2.0.0

flutter:
  uses-material-design: true
