include: package:surf_lint_rules/analysis_options.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  rules:
    - avoid-unused-parameters
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - prefer-intl-name
    - provide-correct-intl-args

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
