name: redux_elementary_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.1"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  elementary: ^1.2.0
  fast_immutable_collections: ^7.2.1
  flutter:
    sdk: flutter
  freezed: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.1.5
  meta: ^1.7.0
  provider: ^6.0.2
  redux: ^5.0.0
  redux_epics: ^0.15.1
  shared_preferences: ^2.0.6

dev_dependencies:
  mocktail: ^0.3.0
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  test_api: 0.4.9

flutter:
  uses-material-design: true
