name: counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  elementary: ^3.1.1
  elementary_helper: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  elementary_test:
    path: ../
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  mjk_lint_rules: ^2.0.0

flutter:
  uses-material-design: true
