site_name: Elementary
theme:
  name: material
  favicon: images/favicon.png
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Libraries overview:
    - Elementary:
      - Intro: libs/elementary/intro.md
      - Overview: libs/elementary/overview.md
      - Widget Model: libs/elementary/widget-model.md
      - ElementaryModel: libs/elementary/model.md
      - ElementaryWidget: libs/elementary/widget.md
      - Recommendations: libs/elementary/recommendations.md
    - Elementary-helper:
      - Intro: libs/elementary-helper/intro.md
      - Publishers: libs/elementary-helper/publishers.md
      - Subscribers: libs/elementary-helper/subscribers.md
    - Elementary-test:
      - Intro: libs/elementary-test/intro.md
      - Overview: libs/elementary-test/overview.md
  - Tutorials:
    - Quick Start:
      - Tooling: tutorials/qs/tooling.md
      - Dependencies: tutorials/qs/dependencies.md
      - Implementation: tutorials/qs/implementation.md
      - Tests: tutorials/qs/tests.md
  - License: license.md
  - About: about.md