name: elementary_helper
description: A library with a bunch of helpers for elementary library, such as publisher-subscriber implementations, wrappers, etc.
version: 1.0.1
repository: "https://github.com/Elementary-team/flutter-elementary/tree/main/packages/elementary_helper"
issue_tracker: "https://github.com/Elementary-team/flutter-elementary/issues"
homepage: "https://github.com/Elementary-team/flutter-elementary"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.0
  mjk_lint_rules: ^2.0.0
