name: elementary analysis

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/elementary/**"
      - ".github/workflows/elementary.yaml"

  push:
    branches:
      - main
    paths:
      - "packages/elementary/**"
      - ".github/workflows/elementary.yaml"

jobs:
  analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/elementary


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Content
        id: check_license
        uses: andstor/file-existence-action@v1
        with:
          files: "LICENSE, README.md, example, CHANGELOG.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo Content is ok!

      - name: Check Description
        run: echo | grep -q Description README.md ; echo $?

      - name: Check Overview
        run: echo | grep -q Overview README.md ; echo $?

      - name: Check Technical Overview
        run: echo | grep -q 'Technical Overview' README.md ; echo $?

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator
      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: flutter format --set-exit-if-changed .

      - name: Run package analyzer
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/elementary/

  testing:
    needs: analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/elementary

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -F elementary

  build_android_example:
    needs: analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/elementary

    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: |
          cd example
          flutter pub get
          flutter build apk

  build_ios_example:
    needs: analysis
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/elementary

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd example
          flutter pub get
          flutter build ios --release --no-codesign
